name: clean_architecture_stack
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.7.0
  io: ^1.0.5
  chalkdart: ^3.0.5 

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  clean_architecture_stack: bin/clean_architecture_stack.dart